version: '3'
services:
  vault:
    image: vault:1.13.0
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: my-root-token  # Token para desarrollo
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK

  app:
    build: .
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: my-root-token
    depends_on:
      - vault
    ports:
      - "9010:9010"
