version: '3.8'
services:
  vault:
    image: vault:1.13.0
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root_token
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8200:8200"
    command: vault server -dev -dev-root-token-id=j3H8p2T5mQ9bF6vY4wZ1R0cG7S
    volumes:
      - ./vault:/vault

  springboot-app:
    image: springboot-app:latest
    build: .
    ports:
      - "9010:9010"
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: j3H8p2T5mQ9bF6vY4wZ1R0cG7S
      SPRING_CLOUD_VAULT_HOST: vault
      SPRING_CLOUD_VAULT_PORT: 8200
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - vault
